/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.webjars.bootstrap)
    api(libs.org.webjars.webjars.locator)
    api(libs.mysql.mysql.connector.java)
    api(libs.ir.ghasemkiani.persiancalendar)
    api(libs.org.apache.logging.log4j.log4j.api)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.mockito.mockito.core)
}

group = "com.viracam.backend"
version = "1.0-SNAPSHOT"
description = "ViraCamBackEnd"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
